---
- name: Load Gnome Tweaks 
  become_user: "{{user}}"
  command: dconf load / < tasks/desktop/saved_settings.dconf

## Broken for some reason...
# - name: Restart Gnome
#   become_user: "{{user}}"
#   command: "dbus-send --type=method_call --print-reply --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'global.reexec_self()'"