---
- name: Clean artifact path
  file:
    state: absent
    path: "/tmp/theme/"

- name: Download Repos from Git
  become_user: "{{user}}"
  git:
    repo: https://github.com/vinceliuice/Canta-theme.git
    dest: /tmp/theme/
    update: yes

- name: Run install script
  become_user: "{{user}}"
  command: /tmp/theme/install.sh

- name: Clean artifact path
  file:
    state: absent
    path: "/tmp/theme/"