---
# - pip:
#     name: "{{item}}"
#   with_items:
#     - requests
#     - boto3
#     - xlsxwriter
#     - flask

- pip:
    name: "{{item}}"
    executable: pip3
  with_items:
    - requests
    - boto3
    - xlsxwriter
    - flask
    - pylint
    # - parallel-ssh