- hosts: localhost
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/misc/apt-packages.yml
    - include: tasks/desktop/gnome-extensions/gnome-extensions.yml
      with_items:
      - "{{gnome_extensions}}"
    - include: tasks/desktop/install-theme.yml
    - include: tasks/desktop/gnome-tweaks.yml

    - include: tasks/install-github-release.yml
