- hosts: localhost
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/cron/setup.yml
    - include: tasks/git/setup.yml
    - include: tasks/misc/apt-packages.yml
    - include: tasks/apps/vscode/install.yml
    - include: tasks/apps/vim/install.yml
    - include: tasks/apps/remmina/install.yml
    - include: tasks/system/power-management.yml
    - include: tasks/desktop/setup.yml
    - include: tasks/desktop/plank.yml



