- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - script: scripts/git-user-setup.sh
    - include: tasks/simple-apt-packages.yml
    - include: tasks/users.yml
    - include: tasks/cron-jobs.yml
