- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/cron/setup.yml
    - include: tasks/git/setup.yml
    - include: tasks/misc/apt-packages.yml
    - include: tasks/vscode/install.yml
    - include: tasks/system/power-management.yml
    - include: tasks/desktop/setup.yml
    - include: tasks/desktop/plank.yml



