- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: Setup git user preferences
      become_user: siobrien
      script: scripts/git-user-setup.sh

    - include: tasks/simple-apt-packages.yml

    - include: tasks/cron-jobs.yml

    - include: tasks/vscode/install.yml

    - include: tasks/system/power-management.yml

    - include: tasks/plank/install.yml
