- hosts: localhost
  pre_tasks:
    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: False

  tasks:
    # - include: tasks/test.yml  
    - name: Setup git user preferences
      script: scripts/git-user-setup.sh
      
    - include: tasks/simple-apt-packages.yml
    - include: tasks/cron-jobs.yml
    - include: tasks/vscode/install.yml
    - include: tasks/system/power-management.yml
