- name: Install Visual Studio Code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868

- name: Install Visual Studio Code Extensions
  become_user: "{{user}}"
  script: tasks/apps/vscode/install-extensions.sh
