- name: Install apt packages
  apt: name={{item}}
  with_items:
    - htop
    - gdebi
    - vim
    - tree
    - ubuntu-wallpapers*
    - xclip

- name: Install deb packages
  apt: deb={{item}}
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
