- name: Install bosh dependencies
  apt: name={{item}}
  with_items:
    - build-essential
    - zlibc
    - zlib1g-dev
    - ruby
    - ruby-dev
    - openssl
    - libxslt-dev
    - libxml2-dev
    - libssl-dev
    - libreadline6-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
  ignore_errors: yes

