- name: Get pivnet-cli release
  uri:
    url: https://api.github.com/repos/pivotal-cf/pivnet-cli/releases/{{pivnet_cli_version}}
    return_content: yes
    body_format: json
  register: release_info

- name: Get release download URL
  set_fact:
    #  pivnet_release_url: "{{ release_info.json | json_query('assets[?contains(name, `linux`)].browser_download_url') | join('') }}"
     pivnet_release_url: "{{ release_info.json | to_json | from_json | json_query('assets[?contains(name, `linux`)].browser_download_url') | join('') }}"

- debug:
    msg: "Downloading release from: {{pivnet_release_url}}"

- name: Download pivnet-cli
  get_url:
    url: "{{pivnet_release_url}}"
    dest: /usr/local/bin/pivnet
    mode: 0755
