- name: Install Plank
  apt:
    name: plank

- name: Add Plank to startup apps
  become_user: "{{user}}"
  copy:
    src: /usr/share/applications/plank.desktop
    dest: /home/{{user}}/.config/autostart
    mode: 0664

- name: Setup Plank
  become_user: "{{user}}"
  script: tasks/desktop/setup-plank.sh