- name: Add Papirus apt repositories
  apt_repository:
    repo: ppa:papirus/papirus
    codename: "{{ubuntu_codename}}"

- name: Install Papirus
  apt:
    name: papirus-icon-theme

- name: Install Papirus Folders
  apt:
    name: papirus-folders

- name: Setup Papirus Folder Color
  command: papirus-folders -C green --theme Papirus-Dark

- name: Setup Desktop Settings
  become_user: "{{user}}"
  script: tasks/desktop/setup-desktop.sh