- name: Install TLP
  become: true
  apt:
    name: tlp

- name: Install Powertop
  become: true
  apt:
    name: powertop

- name: Set monitor refresh rate
  become_user: siobrien
  copy:
    src: tasks/system/monitors.xml
    dest: ~/.config