- name: Add Remmina PPA
  apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next
    codename: "{{ubuntu_codename}}"

- name: Install Remmina
  apt: name={{item}}
  with_items:
    - remmina
    - remmina-plugin-rdp
    - libfreerdp-plugins-standard
  ignore_errors: yes # Remina comes with 19.04 and libfreerdp-plugins-standard isn't available