- name: Install apt packages
  apt:
    name:
      - htop
      - gdebi
      - tree
      - ubuntu-wallpapers*
      - mint-backgrounds-*
      - shutter
      - jq

- name: Install Chrome 
  apt: 
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install Zoom
  apt: 
    deb: https://zoom.us/client/latest/zoom_amd64.deb

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
